export enum UsageUnitModel {
  CENTIMETER = 'CENTIMETER',
  SQUARE_METER = 'SQUARE_METER',
  LINEAR_METER = 'LINEAR_METER',
  UNIT = 'UNIT',
}

export enum QuotationStatusModel {
  WAITING = 'WAITING',
  ACCEPTED = 'ACCEPTED',
  DENIED = 'DENIED',
}

export enum OrderStatusModel {
  WAITING = 'WAITING',
  IN_PRODUCTION = 'IN_PRODUCTION',
  IN_ASSEMBLY = 'IN_ASSEMBLY',
  IN_DELIVERY = 'IN_DELIVERY',
  INSTALLED = 'INSTALLED',
}

export enum PaymentTypeModel {
  AT_SIGNATURE = 'AT_SIGNATURE',
  AT_CONSTRUCTION_LICENCE_OBTENTION = 'AT_CONSTRUCTION_LICENCE_OBTENTION',
  AT_SITE_OPENING = 'AT_SITE_OPENING',
  AT_FOUNDATION_COMPLETION = 'AT_FOUNDATION_COMPLETION',
  AT_WALLS_COMPLETION = 'AT_WALLS_COMPLETION',
  AT_WATER_AIR_PUT_OUT = 'AT_WATER_AIR_PUT_OUT',
  AT_EQUIPMENT_WORK_COMPLETION = 'AT_EQUIPMENT_WORK_COMPLETION',
  AT_KEY_HANDING = 'AT_KEY_HANDING',
}
